name: Build Pake App
on:
  workflow_dispatch: # Позволяет запускать сборку вручную

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Pake CLI
        run: npm install -g pake-cli

      - name: Build Twitter App
        run: pake https://x.com --name Twitter --inject styles.css

      - name: Upload Application
        uses: actions/upload-artifact@v4
        with:
          name: Twitter-Windows
          path: "*.exe" # Сохраняет готовый установщик
